#tomcat image provided from docker.io
FROM gitlab/gitlab-ce

LABEL maintainer="jhumes@ti.com"

ARG UID
ARG GID
ARG USR
ARG IMG_USR_HOME
ARG IMG_USR_SHELL

RUN groupadd -g "${GID}" "${USR}"
RUN useradd -u "${UID}" -g "${GID}" -d ${IMG_USR_HOME} -s ${IMG_USR_SHELL} ${USR}
#COPY dist/manager-context.xml /usr/local/tomcat/webapps/manager/META-INF/context.xml
#COPY dist/manager-web.xml /usr/local/tomcat/webapps/manager/WEB-INF/web.xml
#RUN rm -fr /usr/local/tomcat/webapps/examples
#RUN rm -fr /usr/local/tomcat/webapps/docs
#RUN mkdir /usr/local/tomcat/properties
#RUN chown -R ${USR}:${USR} /usr/local/tomcat
#RUN chown -R ${USR}:${USR} /opt/java
RUN apt-get update 
RUN apt-get -y install sudo
RUN apt-get -y install vim
RUN apt-get -y install git
RUN sed -i 's/%sudo.*$/%sudo  ALL=(ALL) NOPASSWD: ALL/g' /etc/sudoers
RUN usermod -aG sudo ${USR}

#RUN mkdir /usr/local/tomcat/tempcerts
#RUN openssl s_client -connect ubid-prod.itg.ti.com:636 </dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > /usr/local/tomcat/tempcerts/ubid-prod.itg.ti.com.crt; ls -lart /usr/local/tomcat/tempcerts
#RUN cd $JAVA_HOME/conf/security \
#    && keytool -cacerts -storepass changeit -noprompt -trustcacerts -importcert -alias ldapcert -file /usr/local/tomcat/tempcerts/ubid-prod.itg.ti.com.crt

USER ${USR}

EXPOSE _WELL_KNOWN_HTTP_PORT_
EXPOSE _WELL_KNOWN_HTTPS_PORT_
